# Generated by Django 4.1.7 on 2023-03-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='One_Bread_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_bread_name', models.CharField(max_length=255)),
                ('one_bread_embedding', models.BinaryField()),
                ('one_bread_time', models.IntegerField()),
                ('one_bread_waitingـtime', models.IntegerField()),
                ('one_bread_created_at', models.TimeField(auto_now_add=True)),
                ('one_bread_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('embedding', models.BinaryField()),
                ('time', models.IntegerField()),
                ('waitingـtime', models.IntegerField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('bread_number', models.IntegerField()),
            ],
        ),
    ]
