# Generated by Django 4.1.7 on 2023-04-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='one_bread_order',
            old_name='one_bread_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='one_bread_order',
            old_name='one_bread_embedding',
            new_name='embedding',
        ),
        migrations.RenameField(
            model_name='one_bread_order',
            old_name='one_bread_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='one_bread_order',
            old_name='one_bread_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='one_bread_order',
            old_name='one_bread_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='one_bread_order',
            old_name='one_bread_waitingـtime',
            new_name='waitingـtime',
        ),
    ]
